### ISSUE TITLE
Contributing Wasserstein GAN

### ISSUE THREAD

**Issue by TrizteX** [pranjaldatta/PyVision#12]
Paper: [WGAN](https://arxiv.org/abs/1701.07875)
Using code provided [here](https://pytorch.org/tutorials/beginner/dcgan_faces_tutorial.html) for DCGAN as reference. 

Dataset: CelebA dataset

**Comment by pranjaldatta** [comment]
@TrizteX can you please provide details regarding how you are going to go about it? Like what's it gonna be pretrained on, link to  paper that its based on etc?

**Comment by pranjaldatta** [comment]
resolved by PR #18
