### ISSUE TITLE
Contributing U-Net

### ISSUE THREAD

**Issue by ghostpress** [pranjaldatta/PyVision#20]
From [U-Net: Convolutional Networks for Biomedical Image Segmentation](https://arxiv.org/pdf/1505.04597.pdf) (Ronneberger et. al. 2015). Can be filed under Misc.

The networks are trained on the [ISBI](http://brainiac2.mit.edu/isbi_challenge/) 2D EM segmentation challenge dataset.

**Comment by pranjaldatta** [comment]
@ghostpress Sorry for the delay but since we are talking about Image segmentation as a task, wouldn't it better to file it under a separate "segmentation" category under PyVision/pyvision/

**Comment by ghostpress** [comment]
Yes, I was actually thinking the same thing but I wasn't sure if I had to work with the organization already built. Will create a new category with my first commit!
