### ISSUE TITLE
Contributing Neural Style Transfer

### ISSUE THREAD

**Issue by Anushka0805** [pranjaldatta/PyVision#7]

**Comment by pranjaldatta** [comment]
@Anushka0805 can you please provide details regarding how you are going to go about it? Like what's it gonna be pretrained on, any particular paper that its based on etc?

**Comment by Anushka0805** [comment]
It's based on the paper [https://arxiv.org/pdf/1508.06576.pdf] 'A Neural Algorithm of Artistic Style'
